# Generated by Django 5.2.6 on 2025-09-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_quote_reference_quote_sermon_source_sermon_series_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, help_text="e.g., 'Special Service', 'Conference', 'Youth Program'", max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the event.', null=True, upload_to='event_images/'),
        ),
    ]
