# Generated by Django 5.2.6 on 2025-09-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_category_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='highlight_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
