# Generated by Django 5.2.6 on 2026-01-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sermon_highlight_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
