# Generated by Django 5.2.6 on 2025-09-09 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_contactmessage_number_contactmessage_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='number',
            new_name='phone',
        ),
    ]
